name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build and release dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install python-semantic-release toml

      - name: Configure Poetry (Optional, if using Poetry for project management)
        run: |
          poetry config virtualenvs.create false

      - name: Install project dependencies (using poetry)
        run: poetry install --no-root

      - name: Run semantic-release (to create tag only)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: semantic-release-bot
          GIT_AUTHOR_EMAIL: ci-bot@example.com
          GIT_COMMITTER_NAME: semantic-release-bot
          GIT_COMMITTER_EMAIL: ci-bot@example.com
        run: |
          semantic-release version
